version: "3.7"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  cart-service:
    build: .
    container_name: hexagonal-cart-service
    ports:
      - "8000:8000"
    environment:
      - MONGO_DSN=mongodb://mongo:27017