// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/tomkdickinson/hexagonal-cart-service/internal/api"
	"github.com/tomkdickinson/hexagonal-cart-service/internal/cart"
	"github.com/tomkdickinson/hexagonal-cart-service/internal/storage/file"
)

// Injectors from inject_app.go:

func handlersWithFileStorage() (*api.Handlers, error) {
	cartRepository := file.ProvideCartRepository()
	service := cart.ProvideService(cartRepository)
	handlers := api.ProvideHandlers(service)
	return handlers, nil
}
